/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_AT = 2,
  aux_sym_directive_token1 = 3,
  anon_sym_speed_COLON = 4,
  anon_sym_jitter_COLON = 5,
  anon_sym_wait_COLON = 6,
  anon_sym_shell_COLON = 7,
  anon_sym_size_COLON = 8,
  anon_sym_COLON = 9,
  anon_sym_POUND = 10,
  sym_comment_text = 11,
  anon_sym_DOLLAR = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_esc = 15,
  anon_sym_space = 16,
  anon_sym_ret = 17,
  anon_sym_return = 18,
  anon_sym_enter = 19,
  anon_sym_tab = 20,
  anon_sym_backspace = 21,
  anon_sym_bs = 22,
  aux_sym_key_spec_token1 = 23,
  anon_sym_up = 24,
  anon_sym_down = 25,
  anon_sym_left = 26,
  anon_sym_right = 27,
  anon_sym_home = 28,
  anon_sym_end = 29,
  anon_sym_pageup = 30,
  anon_sym_pgup = 31,
  anon_sym_pagedown = 32,
  anon_sym_pgdn = 33,
  anon_sym_insert = 34,
  anon_sym_ins = 35,
  anon_sym_delete = 36,
  anon_sym_del = 37,
  sym_modifier_combo = 38,
  aux_sym_escaped_bracket_token1 = 39,
  aux_sym_escaped_bracket_token2 = 40,
  sym_text = 41,
  sym_float = 42,
  sym_integer = 43,
  sym_shell_path = 44,
  sym_source_file = 45,
  sym__line = 46,
  sym_directive = 47,
  sym_speed_directive = 48,
  sym_jitter_directive = 49,
  sym_wait_directive = 50,
  sym_shell_directive = 51,
  sym_size_directive = 52,
  sym_comment = 53,
  sym_inline_comment = 54,
  sym_type_command = 55,
  sym_type_content = 56,
  sym_special_key = 57,
  sym_key_spec = 58,
  sym_escaped_bracket = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_type_content_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_AT] = "@",
  [aux_sym_directive_token1] = "directive_token1",
  [anon_sym_speed_COLON] = "speed:",
  [anon_sym_jitter_COLON] = "jitter:",
  [anon_sym_wait_COLON] = "wait:",
  [anon_sym_shell_COLON] = "shell:",
  [anon_sym_size_COLON] = "size:",
  [anon_sym_COLON] = ":",
  [anon_sym_POUND] = "#",
  [sym_comment_text] = "comment_text",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_esc] = "esc",
  [anon_sym_space] = "space",
  [anon_sym_ret] = "ret",
  [anon_sym_return] = "return",
  [anon_sym_enter] = "enter",
  [anon_sym_tab] = "tab",
  [anon_sym_backspace] = "backspace",
  [anon_sym_bs] = "bs",
  [aux_sym_key_spec_token1] = "key_spec_token1",
  [anon_sym_up] = "up",
  [anon_sym_down] = "down",
  [anon_sym_left] = "left",
  [anon_sym_right] = "right",
  [anon_sym_home] = "home",
  [anon_sym_end] = "end",
  [anon_sym_pageup] = "pageup",
  [anon_sym_pgup] = "pgup",
  [anon_sym_pagedown] = "pagedown",
  [anon_sym_pgdn] = "pgdn",
  [anon_sym_insert] = "insert",
  [anon_sym_ins] = "ins",
  [anon_sym_delete] = "delete",
  [anon_sym_del] = "del",
  [sym_modifier_combo] = "modifier_combo",
  [aux_sym_escaped_bracket_token1] = "escaped_bracket_token1",
  [aux_sym_escaped_bracket_token2] = "escaped_bracket_token2",
  [sym_text] = "text",
  [sym_float] = "float",
  [sym_integer] = "integer",
  [sym_shell_path] = "shell_path",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_directive] = "directive",
  [sym_speed_directive] = "speed_directive",
  [sym_jitter_directive] = "jitter_directive",
  [sym_wait_directive] = "wait_directive",
  [sym_shell_directive] = "shell_directive",
  [sym_size_directive] = "size_directive",
  [sym_comment] = "comment",
  [sym_inline_comment] = "inline_comment",
  [sym_type_command] = "type_command",
  [sym_type_content] = "type_content",
  [sym_special_key] = "special_key",
  [sym_key_spec] = "key_spec",
  [sym_escaped_bracket] = "escaped_bracket",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_content_repeat1] = "type_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [anon_sym_speed_COLON] = anon_sym_speed_COLON,
  [anon_sym_jitter_COLON] = anon_sym_jitter_COLON,
  [anon_sym_wait_COLON] = anon_sym_wait_COLON,
  [anon_sym_shell_COLON] = anon_sym_shell_COLON,
  [anon_sym_size_COLON] = anon_sym_size_COLON,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_comment_text] = sym_comment_text,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_esc] = anon_sym_esc,
  [anon_sym_space] = anon_sym_space,
  [anon_sym_ret] = anon_sym_ret,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_enter] = anon_sym_enter,
  [anon_sym_tab] = anon_sym_tab,
  [anon_sym_backspace] = anon_sym_backspace,
  [anon_sym_bs] = anon_sym_bs,
  [aux_sym_key_spec_token1] = aux_sym_key_spec_token1,
  [anon_sym_up] = anon_sym_up,
  [anon_sym_down] = anon_sym_down,
  [anon_sym_left] = anon_sym_left,
  [anon_sym_right] = anon_sym_right,
  [anon_sym_home] = anon_sym_home,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_pageup] = anon_sym_pageup,
  [anon_sym_pgup] = anon_sym_pgup,
  [anon_sym_pagedown] = anon_sym_pagedown,
  [anon_sym_pgdn] = anon_sym_pgdn,
  [anon_sym_insert] = anon_sym_insert,
  [anon_sym_ins] = anon_sym_ins,
  [anon_sym_delete] = anon_sym_delete,
  [anon_sym_del] = anon_sym_del,
  [sym_modifier_combo] = sym_modifier_combo,
  [aux_sym_escaped_bracket_token1] = aux_sym_escaped_bracket_token1,
  [aux_sym_escaped_bracket_token2] = aux_sym_escaped_bracket_token2,
  [sym_text] = sym_text,
  [sym_float] = sym_float,
  [sym_integer] = sym_integer,
  [sym_shell_path] = sym_shell_path,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_directive] = sym_directive,
  [sym_speed_directive] = sym_speed_directive,
  [sym_jitter_directive] = sym_jitter_directive,
  [sym_wait_directive] = sym_wait_directive,
  [sym_shell_directive] = sym_shell_directive,
  [sym_size_directive] = sym_size_directive,
  [sym_comment] = sym_comment,
  [sym_inline_comment] = sym_inline_comment,
  [sym_type_command] = sym_type_command,
  [sym_type_content] = sym_type_content,
  [sym_special_key] = sym_special_key,
  [sym_key_spec] = sym_key_spec,
  [sym_escaped_bracket] = sym_escaped_bracket,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_content_repeat1] = aux_sym_type_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_speed_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jitter_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wait_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shell_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_size_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_esc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_space] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ret] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_backspace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bs] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_spec_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_up] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_down] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_left] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_right] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_home] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pageup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pgup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pagedown] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pgdn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_insert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ins] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_delete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_del] = {
    .visible = true,
    .named = false,
  },
  [sym_modifier_combo] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_escaped_bracket_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escaped_bracket_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_shell_path] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_speed_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_jitter_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_wait_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_shell_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_size_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_type_command] = {
    .visible = true,
    .named = true,
  },
  [sym_type_content] = {
    .visible = true,
    .named = true,
  },
  [sym_special_key] = {
    .visible = true,
    .named = true,
  },
  [sym_key_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_bracket] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(139);
      ADVANCE_MAP(
        '\n', 140,
        '#', 150,
        '$', 152,
        '.', 136,
        ':', 149,
        '<', 153,
        '>', 154,
        '@', 141,
        'A', 7,
        'C', 8,
        'F', 15,
        'M', 5,
        'S', 6,
        '\\', 21,
        'a', 11,
        'b', 30,
        'c', 12,
        'd', 54,
        'e', 91,
        'h', 98,
        'i', 92,
        'j', 80,
        'l', 55,
        'm', 9,
        'p', 31,
        'r', 66,
        's', 10,
        't', 32,
        'u', 101,
        'w', 35,
        '\t', 142,
        ' ', 142,
        '+', 14,
        '-', 14,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(140);
      if (lookahead == '<') ADVANCE(153);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0) ADVANCE(205);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(140);
      if (lookahead == '<') ADVANCE(153);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(205);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(140);
      if (lookahead != 0) ADVANCE(151);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'H') ADVANCE(25);
      if (lookahead == 'h') ADVANCE(79);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'L') ADVANCE(28);
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'T') ADVANCE(27);
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'h') ADVANCE(65);
      if (lookahead == 'i') ADVANCE(135);
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(136);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      END_STATE();
    case 15:
      if (lookahead == '1') ADVANCE(164);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(163);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(148);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(146);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(147);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(144);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(145);
      END_STATE();
    case 21:
      if (lookahead == '<') ADVANCE(203);
      if (lookahead == '>') ADVANCE(204);
      END_STATE();
    case 22:
      ADVANCE_MAP(
        'A', 182,
        'C', 183,
        'F', 188,
        'M', 180,
        'S', 181,
        'a', 186,
        'b', 191,
        'c', 187,
        'd', 192,
        'e', 197,
        'h', 199,
        'i', 198,
        'l', 195,
        'm', 184,
        'p', 190,
        'r', 193,
        's', 185,
        't', 189,
        'u', 200,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= ']') ||
          ('f' <= lookahead && lookahead <= 'z')) ADVANCE(179);
      END_STATE();
    case 23:
      if (lookahead == 'A') ADVANCE(4);
      END_STATE();
    case 24:
      if (lookahead == 'F') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'I') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(4);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(26);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(4);
      END_STATE();
    case 29:
      if (lookahead == 'T') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 's') ADVANCE(162);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead == 'g') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(81);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 38:
      if (lookahead == 'b') ADVANCE(179);
      END_STATE();
    case 39:
      if (lookahead == 'b') ADVANCE(160);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(179);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(82);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(155);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 46:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(179);
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(170);
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(100);
      if (lookahead == 'u') ADVANCE(104);
      END_STATE();
    case 50:
      if (lookahead == 'd') ADVANCE(95);
      if (lookahead == 'u') ADVANCE(103);
      END_STATE();
    case 51:
      if (lookahead == 'd') ADVANCE(93);
      if (lookahead == 'u') ADVANCE(102);
      END_STATE();
    case 52:
      if (lookahead == 'd') ADVANCE(19);
      END_STATE();
    case 53:
      if (lookahead == 'd') ADVANCE(99);
      if (lookahead == 'u') ADVANCE(102);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(85);
      if (lookahead == 'o') ADVANCE(132);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(179);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(169);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(156);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(177);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(161);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(88);
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(121);
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 70:
      if (lookahead == 'f') ADVANCE(120);
      END_STATE();
    case 71:
      if (lookahead == 'f') ADVANCE(122);
      END_STATE();
    case 72:
      if (lookahead == 'f') ADVANCE(119);
      END_STATE();
    case 73:
      if (lookahead == 'g') ADVANCE(77);
      END_STATE();
    case 74:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 75:
      if (lookahead == 'g') ADVANCE(78);
      END_STATE();
    case 76:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 77:
      if (lookahead == 'h') ADVANCE(124);
      END_STATE();
    case 78:
      if (lookahead == 'h') ADVANCE(119);
      END_STATE();
    case 79:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 80:
      if (lookahead == 'i') ADVANCE(128);
      END_STATE();
    case 81:
      if (lookahead == 'i') ADVANCE(126);
      END_STATE();
    case 82:
      if (lookahead == 'k') ADVANCE(117);
      END_STATE();
    case 83:
      if (lookahead == 'k') ADVANCE(118);
      END_STATE();
    case 84:
      if (lookahead == 'l') ADVANCE(4);
      END_STATE();
    case 85:
      if (lookahead == 'l') ADVANCE(178);
      END_STATE();
    case 86:
      if (lookahead == 'l') ADVANCE(194);
      END_STATE();
    case 87:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 88:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 89:
      if (lookahead == 'm') ADVANCE(57);
      END_STATE();
    case 90:
      if (lookahead == 'm') ADVANCE(56);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(48);
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(179);
      END_STATE();
    case 94:
      if (lookahead == 'n') ADVANCE(166);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(174);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(158);
      END_STATE();
    case 97:
      if (lookahead == 'n') ADVANCE(173);
      END_STATE();
    case 98:
      if (lookahead == 'o') ADVANCE(89);
      END_STATE();
    case 99:
      if (lookahead == 'o') ADVANCE(133);
      END_STATE();
    case 100:
      if (lookahead == 'o') ADVANCE(134);
      END_STATE();
    case 101:
      if (lookahead == 'p') ADVANCE(165);
      END_STATE();
    case 102:
      if (lookahead == 'p') ADVANCE(179);
      END_STATE();
    case 103:
      if (lookahead == 'p') ADVANCE(172);
      END_STATE();
    case 104:
      if (lookahead == 'p') ADVANCE(171);
      END_STATE();
    case 105:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 106:
      if (lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 107:
      if (lookahead == 'r') ADVANCE(179);
      END_STATE();
    case 108:
      if (lookahead == 'r') ADVANCE(159);
      END_STATE();
    case 109:
      if (lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 110:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 111:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 112:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 113:
      if (lookahead == 'r') ADVANCE(119);
      END_STATE();
    case 114:
      if (lookahead == 'r') ADVANCE(125);
      END_STATE();
    case 115:
      if (lookahead == 's') ADVANCE(176);
      END_STATE();
    case 116:
      if (lookahead == 's') ADVANCE(196);
      END_STATE();
    case 117:
      if (lookahead == 's') ADVANCE(106);
      END_STATE();
    case 118:
      if (lookahead == 's') ADVANCE(105);
      END_STATE();
    case 119:
      if (lookahead == 't') ADVANCE(179);
      END_STATE();
    case 120:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 121:
      if (lookahead == 't') ADVANCE(157);
      END_STATE();
    case 122:
      if (lookahead == 't') ADVANCE(167);
      END_STATE();
    case 123:
      if (lookahead == 't') ADVANCE(201);
      END_STATE();
    case 124:
      if (lookahead == 't') ADVANCE(168);
      END_STATE();
    case 125:
      if (lookahead == 't') ADVANCE(175);
      END_STATE();
    case 126:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 127:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 128:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 129:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 130:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 131:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 132:
      if (lookahead == 'w') ADVANCE(94);
      END_STATE();
    case 133:
      if (lookahead == 'w') ADVANCE(93);
      END_STATE();
    case 134:
      if (lookahead == 'w') ADVANCE(97);
      END_STATE();
    case 135:
      if (lookahead == 'z') ADVANCE(58);
      END_STATE();
    case 136:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(207);
      END_STATE();
    case 137:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(208);
      END_STATE();
    case 138:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(209);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '\\') ADVANCE(205);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_speed_COLON);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_jitter_COLON);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_wait_COLON);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_shell_COLON);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_size_COLON);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_esc);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_space);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_ret);
      if (lookahead == 'u') ADVANCE(111);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_enter);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_tab);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_backspace);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_bs);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_key_spec_token1);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_key_spec_token1);
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(163);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_up);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_down);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_left);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_right);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_home);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_pageup);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_pgup);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_pagedown);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_pgdn);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_insert);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_ins);
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_delete);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_del);
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_modifier_combo);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'H') ADVANCE(25);
      if (lookahead == 'h') ADVANCE(79);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'L') ADVANCE(28);
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'T') ADVANCE(27);
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'h') ADVANCE(79);
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(120);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == '1') ADVANCE(202);
      if (('2' <= lookahead && lookahead <= '9')) ADVANCE(179);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'a') ADVANCE(46);
      if (lookahead == 's') ADVANCE(179);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'e') ADVANCE(86);
      if (lookahead == 'o') ADVANCE(133);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'e') ADVANCE(123);
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'n') ADVANCE(47);
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'n') ADVANCE(116);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'o') ADVANCE(90);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'p') ADVANCE(179);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (lookahead == 'u') ADVANCE(110);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_modifier_combo);
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(179);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(aux_sym_escaped_bracket_token1);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(aux_sym_escaped_bracket_token2);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '\\') ADVANCE(205);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '.') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(207);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(208);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_shell_path);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#') ADVANCE(209);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 138},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 13},
  [26] = {.lex_state = 137},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 137},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_directive_token1] = ACTIONS(1),
    [anon_sym_speed_COLON] = ACTIONS(1),
    [anon_sym_jitter_COLON] = ACTIONS(1),
    [anon_sym_wait_COLON] = ACTIONS(1),
    [anon_sym_shell_COLON] = ACTIONS(1),
    [anon_sym_size_COLON] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_esc] = ACTIONS(1),
    [anon_sym_space] = ACTIONS(1),
    [anon_sym_ret] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_enter] = ACTIONS(1),
    [anon_sym_tab] = ACTIONS(1),
    [anon_sym_backspace] = ACTIONS(1),
    [anon_sym_bs] = ACTIONS(1),
    [aux_sym_key_spec_token1] = ACTIONS(1),
    [anon_sym_up] = ACTIONS(1),
    [anon_sym_down] = ACTIONS(1),
    [anon_sym_left] = ACTIONS(1),
    [anon_sym_right] = ACTIONS(1),
    [anon_sym_home] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_pageup] = ACTIONS(1),
    [anon_sym_pgup] = ACTIONS(1),
    [anon_sym_pagedown] = ACTIONS(1),
    [anon_sym_pgdn] = ACTIONS(1),
    [anon_sym_insert] = ACTIONS(1),
    [anon_sym_ins] = ACTIONS(1),
    [anon_sym_delete] = ACTIONS(1),
    [anon_sym_del] = ACTIONS(1),
    [sym_modifier_combo] = ACTIONS(1),
    [aux_sym_escaped_bracket_token1] = ACTIONS(1),
    [aux_sym_escaped_bracket_token2] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym__line] = STATE(5),
    [sym_directive] = STATE(27),
    [sym_comment] = STATE(27),
    [sym_type_command] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    STATE(38), 1,
      sym_key_spec,
    ACTIONS(15), 3,
      anon_sym_ret,
      anon_sym_ins,
      anon_sym_del,
    ACTIONS(13), 21,
      anon_sym_esc,
      anon_sym_space,
      anon_sym_return,
      anon_sym_enter,
      anon_sym_tab,
      anon_sym_backspace,
      anon_sym_bs,
      aux_sym_key_spec_token1,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_home,
      anon_sym_end,
      anon_sym_pageup,
      anon_sym_pgup,
      anon_sym_pagedown,
      anon_sym_pgdn,
      anon_sym_insert,
      anon_sym_delete,
      sym_modifier_combo,
  [32] = 7,
    ACTIONS(17), 1,
      aux_sym_directive_token1,
    ACTIONS(19), 1,
      anon_sym_speed_COLON,
    ACTIONS(21), 1,
      anon_sym_jitter_COLON,
    ACTIONS(23), 1,
      anon_sym_wait_COLON,
    ACTIONS(25), 1,
      anon_sym_shell_COLON,
    ACTIONS(27), 1,
      anon_sym_size_COLON,
    STATE(14), 5,
      sym_speed_directive,
      sym_jitter_directive,
      sym_wait_directive,
      sym_shell_directive,
      sym_size_directive,
  [58] = 7,
    ACTIONS(29), 1,
      anon_sym_LF,
    ACTIONS(31), 1,
      aux_sym_directive_token1,
    ACTIONS(33), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      sym_text,
    STATE(28), 1,
      sym_type_content,
    ACTIONS(35), 2,
      aux_sym_escaped_bracket_token1,
      aux_sym_escaped_bracket_token2,
    STATE(9), 3,
      sym_special_key,
      sym_escaped_bracket,
      aux_sym_type_content_repeat1,
  [83] = 7,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_LF,
    STATE(6), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(27), 3,
      sym_directive,
      sym_comment,
      sym_type_command,
  [108] = 7,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_LF,
    ACTIONS(48), 1,
      anon_sym_AT,
    ACTIONS(51), 1,
      anon_sym_POUND,
    ACTIONS(54), 1,
      anon_sym_DOLLAR,
    STATE(6), 2,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(27), 3,
      sym_directive,
      sym_comment,
      sym_type_command,
  [133] = 6,
    ACTIONS(19), 1,
      anon_sym_speed_COLON,
    ACTIONS(21), 1,
      anon_sym_jitter_COLON,
    ACTIONS(23), 1,
      anon_sym_wait_COLON,
    ACTIONS(25), 1,
      anon_sym_shell_COLON,
    ACTIONS(27), 1,
      anon_sym_size_COLON,
    STATE(15), 5,
      sym_speed_directive,
      sym_jitter_directive,
      sym_wait_directive,
      sym_shell_directive,
      sym_size_directive,
  [156] = 6,
    ACTIONS(33), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      anon_sym_LF,
    ACTIONS(59), 1,
      sym_text,
    STATE(33), 1,
      sym_type_content,
    ACTIONS(35), 2,
      aux_sym_escaped_bracket_token1,
      aux_sym_escaped_bracket_token2,
    STATE(9), 3,
      sym_special_key,
      sym_escaped_bracket,
      aux_sym_type_content_repeat1,
  [178] = 5,
    ACTIONS(33), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LF,
    ACTIONS(63), 1,
      sym_text,
    ACTIONS(35), 2,
      aux_sym_escaped_bracket_token1,
      aux_sym_escaped_bracket_token2,
    STATE(10), 3,
      sym_special_key,
      sym_escaped_bracket,
      aux_sym_type_content_repeat1,
  [197] = 5,
    ACTIONS(65), 1,
      anon_sym_LF,
    ACTIONS(67), 1,
      anon_sym_LT,
    ACTIONS(73), 1,
      sym_text,
    ACTIONS(70), 2,
      aux_sym_escaped_bracket_token1,
      aux_sym_escaped_bracket_token2,
    STATE(10), 3,
      sym_special_key,
      sym_escaped_bracket,
      aux_sym_type_content_repeat1,
  [216] = 1,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_AT,
      anon_sym_POUND,
      anon_sym_DOLLAR,
  [224] = 1,
    ACTIONS(78), 5,
      anon_sym_LF,
      anon_sym_LT,
      aux_sym_escaped_bracket_token1,
      aux_sym_escaped_bracket_token2,
      sym_text,
  [232] = 1,
    ACTIONS(80), 5,
      anon_sym_LF,
      anon_sym_LT,
      aux_sym_escaped_bracket_token1,
      aux_sym_escaped_bracket_token2,
      sym_text,
  [240] = 3,
    ACTIONS(82), 1,
      anon_sym_LF,
    ACTIONS(84), 1,
      aux_sym_directive_token1,
    STATE(32), 1,
      sym_inline_comment,
  [250] = 3,
    ACTIONS(84), 1,
      aux_sym_directive_token1,
    ACTIONS(86), 1,
      anon_sym_LF,
    STATE(37), 1,
      sym_inline_comment,
  [260] = 2,
    ACTIONS(88), 1,
      anon_sym_LF,
    ACTIONS(90), 1,
      sym_comment_text,
  [267] = 1,
    ACTIONS(92), 2,
      anon_sym_LF,
      aux_sym_directive_token1,
  [272] = 1,
    ACTIONS(94), 2,
      anon_sym_LF,
      aux_sym_directive_token1,
  [277] = 1,
    ACTIONS(96), 2,
      anon_sym_LF,
      aux_sym_directive_token1,
  [282] = 2,
    ACTIONS(98), 1,
      anon_sym_LF,
    ACTIONS(100), 1,
      sym_comment_text,
  [289] = 1,
    ACTIONS(102), 2,
      anon_sym_LF,
      aux_sym_directive_token1,
  [294] = 1,
    ACTIONS(104), 2,
      anon_sym_LF,
      aux_sym_directive_token1,
  [299] = 1,
    ACTIONS(106), 1,
      sym_shell_path,
  [303] = 1,
    ACTIONS(108), 1,
      sym_float,
  [307] = 1,
    ACTIONS(110), 1,
      sym_float,
  [311] = 1,
    ACTIONS(112), 1,
      sym_integer,
  [315] = 1,
    ACTIONS(114), 1,
      anon_sym_LF,
  [319] = 1,
    ACTIONS(57), 1,
      anon_sym_LF,
  [323] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [327] = 1,
    ACTIONS(118), 1,
      anon_sym_LF,
  [331] = 1,
    ACTIONS(120), 1,
      sym_float,
  [335] = 1,
    ACTIONS(86), 1,
      anon_sym_LF,
  [339] = 1,
    ACTIONS(122), 1,
      anon_sym_LF,
  [343] = 1,
    ACTIONS(124), 1,
      anon_sym_POUND,
  [347] = 1,
    ACTIONS(126), 1,
      anon_sym_COLON,
  [351] = 1,
    ACTIONS(128), 1,
      anon_sym_GT,
  [355] = 1,
    ACTIONS(130), 1,
      anon_sym_LF,
  [359] = 1,
    ACTIONS(132), 1,
      anon_sym_GT,
  [363] = 1,
    ACTIONS(134), 1,
      sym_integer,
  [367] = 1,
    ACTIONS(136), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 83,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 133,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 178,
  [SMALL_STATE(10)] = 197,
  [SMALL_STATE(11)] = 216,
  [SMALL_STATE(12)] = 224,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 250,
  [SMALL_STATE(16)] = 260,
  [SMALL_STATE(17)] = 267,
  [SMALL_STATE(18)] = 272,
  [SMALL_STATE(19)] = 277,
  [SMALL_STATE(20)] = 282,
  [SMALL_STATE(21)] = 289,
  [SMALL_STATE(22)] = 294,
  [SMALL_STATE(23)] = 299,
  [SMALL_STATE(24)] = 303,
  [SMALL_STATE(25)] = 307,
  [SMALL_STATE(26)] = 311,
  [SMALL_STATE(27)] = 315,
  [SMALL_STATE(28)] = 319,
  [SMALL_STATE(29)] = 323,
  [SMALL_STATE(30)] = 327,
  [SMALL_STATE(31)] = 331,
  [SMALL_STATE(32)] = 335,
  [SMALL_STATE(33)] = 339,
  [SMALL_STATE(34)] = 343,
  [SMALL_STATE(35)] = 347,
  [SMALL_STATE(36)] = 351,
  [SMALL_STATE(37)] = 355,
  [SMALL_STATE(38)] = 359,
  [SMALL_STATE(39)] = 363,
  [SMALL_STATE(40)] = 367,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_command, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_command, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_content, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_content_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_content_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_content_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_content_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_bracket, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_key, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_speed_directive, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jitter_directive, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wait_directive, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_comment, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shell_directive, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_size_directive, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_command, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_spec, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_typecast(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "typecast",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
